vim.filetype.add({
  extension = {
    rb = 'ruby',
    rbw = 'ruby',
    gem = 'ruby',
    gemspec = 'ruby',
    builder = 'ruby',
    rxml = 'ruby',
    rjs = 'ruby',
    rake = 'ruby',
    erb = 'eruby',
    rhtml = 'eruby',
    jbuilder = 'ruby',
    podspec = 'ruby',
    iam = 'ruby',
  },
  filename = {
    ['Rakefile'] = 'ruby',
    ['Podfile'] = 'ruby',
    ['Gemfile'] = 'ruby',
    ['Guardfile'] = 'ruby',
    ['Fastfile'] = 'ruby',
    ['Appfile'] = 'ruby',
    ['Snapfile'] = 'ruby',
    ['Scanfile'] = 'ruby',
    ['Gymfile'] = 'ruby',
    ['Matchfile'] = 'ruby',
    ['Deliverfile'] = 'ruby',
    ['Pluginfile'] = 'ruby',
    ['Dangerfile'] = 'ruby',
  },
})