[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = ['<Plug>(quickrun)']
depends = ['vimproc.vim']
hook_add = '''
  let g:loaded_quicklaunch = 1
  let g:quickrun_config = get(g:, 'quickrun_config', {})
  let g:quickrun_config = {
      \ "*": {"runner": "vimproc"},
      \ }
  let g:quickrun_config.markdown = {
        \ 'outputter' : 'null',
        \ 'command'   : 'open',
        \ 'cmdopt'    : '-a',
        \ 'args'      : 'Marked\ 2',
        \ 'exec'      : '%c %o %a %s',
        \ }
  let g:quickrun_config['markdown.slide'] = {
        \ 'outputter' : 'null',
        \ 'command'   : 'open',
        \ 'cmdopt'    : '-a',
        \ 'args'      : 'Deckset',
        \ 'exec'      : '%c %o %a %s',
        \ }
  let g:quickrun_config.swift = {
        \ 'exec' : '/usr/bin/xcrun swift %s'
        \ }
  let g:quickrun_config.plantuml = {
        \ 'outputter' : 'null',
        \ 'cmdopt'    : '-tpng',
        \ 'command'   : 'plantuml',
        \ 'exec'      : '%c %o %s; open *.png',
        \ }
  let g:quickrun_config.rust = {
        \ 'exec' : 'cargo run'
        \ }
  silent! nmap <unique> <C-x><C-x> <Plug>(quickrun)
'''

[[plugins]]
repo = 'github/copilot.vim'
hook_add = '''
let b:copilot_enabled = v:true
noremap <C-c><Tab> :Copilot<CR>
'''
on_cmd = 'Copilot'

# for markdown
[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
depends = 'tabular'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'giginet/denops-deckset.vim'
on_ft = ['md', 'markdown', 'markdown.slide']
depends = ['denops.vim']
hook_add = '''
let g:deckset#show_slide_numbers=1
let g:deckset#show_slide_count=1
let g:deckset#autoscale=0
let g:deckset#theme="Simple, 2"
noremap <C-s>_ :InsertCodeHighlight<CR>
'''
hook_post_source = '''
augroup DecksetConfiguration
  autocmd!
  au BufNewFile /*/slide/*.md :InsertConfiguration
augroup END
'''

[[plugins]]
repo = "Shougo/denite.nvim"
on_cmd = ['Denite']
hook_source = 'source ~/.config/nvim/userautoload/plugins/plugins-denite.vim'
hook_post_source = '''
  call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>', 'noremap')
'''

[[plugins]]
repo = 'tyru/open-browser-github.vim'
depends = 'open-browser.vim'
on_cmd = ['OpenGithubFile', 'OpenGithubIssue', 'OpenGithubPullReq', 'OpenGithubProject']
hook_add = '''
noremap <silent> <C-g>o :execute line(".") . "OpenGithubFile"<CR>
vnoremap <silent> <C-g>o :'<,'>OpenGithubFile<CR>
let g:openbrowser_github_always_use_commit_hash=0
let g:openbrowser_github_url_exists_check="no"

'''

[[plugins]]
repo = 'vim-scripts/tComment'
on_map = ['<C-_><C-_>']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']
hook_add = '''
let NERDTreeShowHidden=1
let NERDTreeIgnore=['\.vim$', '\.git$', '\.DS_Store', '\.idea', '\.build']
'''

[[plugins]]
repo = 'iberianpig/tig-explorer.vim'
depends = 'blose.vim'
on_cmd = ['TigOpenCurrentFile', 'TigOpenProjectRootDir', 'TigGrep', 'TigGrepResume', 'TigBlame']
hook_add = '''
nnoremap <C-g> :TigOpenProjectRootDir<CR>
nnoremap <C-g>l :TigOpenCurrentFile<CR>
nnoremap <C-g>b :TigBlame<CR>
nnoremap <C-g>g :TigGrep<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_i = 1

[[plugins]]
repo = 'keith/investigate.vim'
on_map = ["gK"]
hook_source = '''
  let g:investigate_use_dash = 1
'''

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_i = 1

[[plugins]]
repo = 'tyru/open-browser.vim'
on_i = 1

[[plugins]]
repo = 'dracula/vim'
on_event = ['VimEnter']
hook_post_source = '''
  color dracula
'''

[[plugins]]
repo = 'haya14busa/vim-open-googletranslate'
on_event = ['OpenGoogleTranslate']
depends = 'open-browser.vim'
hook_add = '''
  let g:opengoogletranslate#default_lang = 'ja'
  noremap <C-t> :OpenGoogleTranslate --to=ja --from=en<CR>
'''
