[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = ['<Plug>(quickrun)']
depends = ['vimproc.vim']
hook_add = '''
  let g:loaded_quicklaunch = 1
  let g:quickrun_config = get(g:, 'quickrun_config', {})
  let g:quickrun_config = {
      \ "*": {"runner": "vimproc"},
      \ }
  let g:quickrun_config.markdown = {
        \ 'outputter' : 'null',
        \ 'command'   : 'open',
        \ 'cmdopt'    : '-a',
        \ 'args'      : 'Marked\ 2',
        \ 'exec'      : '%c %o %a %s',
        \ }
  let g:quickrun_config.swift = {
        \ 'exec' : '/usr/bin/xcrun swift %s'
        \ }
  let g:quickrun_config.rust = {
        \ 'exec' : 'cargo run'
        \ }
  silent! nmap <unique> <C-x><C-x> <Plug>(quickrun)
'''

# for markdown
[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
depends = 'tabular'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]] 
repo = "Shougo/denite.nvim"
on_cmd = ['Denite']
hook_source = 'source ~/.config/nvim/userautoload/plugins/plugins-denite.vim'
hook_post_source = '''
  call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>', 'noremap')
'''

[[plugins]]
repo = "lambdalisue/vim-gista"
on_cmd = ['Gista']
on_map = ['<Plug>(gista-']
hook_add = '''
  let g:gista#client#use_git_config_github_username = 1
'''

[[plugins]]
repo = 'vim-scripts/tComment'
on_map = ['<C-_><C-_>']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_i = 1

[[plugins]]
repo = 'keith/investigate.vim'
on_map = ["gK"]
hook_source = '''
  let g:investigate_use_dash = 1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
if = '''has('nvim')'''
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  set completeopt+=noinsert
'''

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_i = 1

[[plugins]]
repo = 'tyru/open-browser.vim'
on_i = 1

[[plugins]]
repo = 'dracula/vim'
on_event = ['VimEnter']
hook_post_source = '''
  color dracula
'''

[[plugins]]
repo = 'haya14busa/vim-open-googletranslate'
on_event = ['OpenGoogleTranslate']
depends = ['open-browser.vim']
hook_add = '''
  let g:opengoogletranslate#default_lang = 'ja'
  noremap <C-t> :OpenGoogleTranslate --to=ja --from=en<CR>
'''

[[plugins]]
repo = 'tpope/vim-git'
on_ft = ['git', 'gitcommit', 'gitconfig', 'gitrebase']
