[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim', 'vim-quickrun']

# for Ruby
[[plugins]]
repo = 'tpope/vim-bundler'

# for Swift
[[plugins]]
repo = 'keith/swift.vim'
hook_source = '''
  let g:syntastic_swift_checkers = ['swiftpm', 'swiftlint']
'''
[[plugins]]
repo = 'apple/swift'
rtp = 'utils/vim'

# for Groovy
[[plugins]]
repo = 'tfnico/vim-gradle'

# for TOML
[[plugins]]
repo = 'cespare/vim-toml'

# for JSON
[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

# for tmux.conf
[[plugins]]
repo = 'tmux-plugins/vim-tmux'

# for Dockerfile
[[plugins]]
repo = 'ekalinin/dockerfile.vim'

# for Jsonnet
[[plugins]]
repo = 'google/vim-jsonnet'

# for modulemap
[[plugins]]
repo = 'compnerd/modulemap-vim'

# for xcconfig
[[plugins]]
repo = 'keith/xcconfig.vim'
