[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = ['<Plug>(quickrun)']
hook_add = '''
  let g:loaded_quicklaunch = 1
  let g:quickrun_config = {
      \ "*": {"runner": "remote/vimproc"},
      \ 'split': '{"rightbelow 10sp"}'
      \ }
  silent! nmap <unique> <C-x><C-x> <Plug>(quickrun)
'''

[[plugins]] 
repo = "Shougo/denite.nvim"
on_cmd = ['Denite']
hook_source = 'source ~/.config/nvim/userautoload/plugins/plugins-denite.vim'
hook_post_source = '''
  call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>', 'noremap')
'''

[[plugins]]
repo = "lambdalisue/vim-gista"
on_cmd = ['Gista']
on_map = ['<Plug>(gista-']
hook_add = '''
  let g:gista#client#use_git_config_github_username = 1
'''

[[plugins]]
repo = 'vim-scripts/tComment'
on_map = ['<C-_><C-_>']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_i = 1

[[plugins]]
repo = 'keith/investigate.vim'
on_map = ["gK"]
hook_source = '''
  let g:investigate_use_dash = 1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
if = '''has('nvim')'''
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  set completeopt+=noinsert
'''

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_i = 1

[[plugins]]
repo = 'tyru/open-browser.vim'
on_i = 1

[[plugins]]
repo = 'dracula/vim'
on_event = ['VimEnter']
hook_post_source = '''
  color dracula
'''

[[plugins]]
repo = 'haya14busa/vim-open-googletranslate'
on_event = ['OpenGoogleTranslate']
depends = ['open-browser.vim']
hook_add = '''
  let g:opengoogletranslate#default_lang = 'ja'
  noremap <C-t> :OpenGoogleTranslate --to=ja --from=en<CR>
'''

[[plugins]]
repo = 'oblitum/rainbow'
hook_add = '''
  let g:rainbow_active = 1
  au MyAutoCmd VimEnter * nested call rainbow#load()
'''

# for Ruby
[[plugins]]
repo = 'tpope/vim-bundler'
on_path = 'Gemfile'

# fot Python
[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']

# for JavaScript
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js']

#for CofeeScript
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

#for TypeScript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

# for HTML
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim.git'
on_ft = ['sass']

[[plugins]]
repo = 'hail2u/vim-css3-syntax.git'
on_ft = ['css']

# for Swift
[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]]
repo = 'landaire/deoplete-swift'
depends = ['deoplete.nvim']
on_ft = ['swift']

# for Scala
[[plugins]]
repo = 'derekwyatt/vim-scala.git'
on_ft = ['scala']

# for Lua
[[plugins]]
repo = 'vim-scripts/lua-support'
on_ft = ['lua']

# for Puppet
[[plugins]]
repo = 'rodjek/vim-puppet'
on_ft = ['puppet']

# for Groovy
[[plugins]]
repo = 'vim-scripts/groovy.vim'
on_ft = ['groovy']

[[plugins]]
repo = 'tfnico/vim-gradle'
on_ft = ['groovy']

# for restructuredText
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['rst', 'md']

[[plugins]]
repo = 'vim-scripts/rest.vim'
on_ft = ['rst']

# for GLSL
[[plugins]]
repo = 'tikhomirov/vim-glsl'
on_ft = ['vert', 'frag', 'fp', 'vp', 'glsl']

# for Markdown
[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'
depends = 'tabular'
on_ft = ['md']
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'AndrewRadev/inline_edit.vim'
on_ft = ['md']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = ['md']
depends = ['context_filetype.vim', 'vim-quickrun']

# for Haskell
[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['hs']

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ['hs']

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['hs']

# for Octave
[[plugins]]
repo = 'jvirtanen/vim-octave'
on_ft = ['octave']

# for TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# for JSON
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

# for tmux.conf
repo = 'tmux-plugins/vim-tmux'
on_ft = ['tmux']

# for Dockerfile
repo = 'ekalinin/dockerfile.vim'
on_ft = ['dockerfile']

# for Jsonnet
repo = 'google/vim-jsonnet'
on_ft = ['jsonnet']

# for modulemap
repo = 'compnerd/modulemap-vim'
on_ft = ['modulemap']
