[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim', 'vim-quickrun']

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'rbgrouleff/bclose.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
if = '''has('nvim')'''
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  call deoplete#custom#option('smart_case', v:true)
  set completeopt+=noinsert
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_source = '''
let g:coc_config_home = '$HOME/.config/nvim'
let g:coc_global_extensions = [
  \'coc-json',
  \'coc-yaml',
  \'coc-sourcekit',
  \'coc-grammarly',
  \'coc-markdownlint',
  \'coc-solargraph',
  \'coc-toml',
  \'coc-sh'
  \]
source $HOME/.config/nvim/coc.vim
'''

# for Ruby
[[plugins]]
repo = 'tpope/vim-bundler'

# for Swift
[[plugins]]
repo = 'keith/swift.vim'
hook_source = '''
  let g:syntastic_swift_checkers = ['swiftpm', 'swiftlint']
'''

# for Groovy
[[plugins]]
repo = 'tfnico/vim-gradle'

# for TOML
[[plugins]]
repo = 'cespare/vim-toml'

# for JSON
[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

# for tmux.conf
[[plugins]]
repo = 'tmux-plugins/vim-tmux'

# for Dockerfile
[[plugins]]
repo = 'ekalinin/dockerfile.vim'

# for Jsonnet
[[plugins]]
repo = 'google/vim-jsonnet'

# for modulemap
[[plugins]]
repo = 'compnerd/modulemap-vim'

# for xcconfig
[[plugins]]
repo = 'keith/xcconfig.vim'

# for Rust
[[plugins]]
repo = 'rust-lang/rust.vim'

# for PlantUML
[[plugins]]
repo = 'aklt/plantuml-syntax'

# for Jinja2
[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'

# for yaml
[[plugins]]
repo = 'stephpy/vim-yaml'

[[plugins]]
repo = 'tpope/vim-git'
on_ft = ['git', 'gitcommit', 'gitconfig', 'gitrebase']
