require('nvim-treesitter.configs').setup {
  ensure_installed = {
    'bash',
    'dockerfile',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'graphql',
    'json',
    'kotlin',
    'lua',
    'make',
    'markdown',
    'markdown_inline',
    'python',
    'ruby',
    'rust',
    'sql',
    'swift',
    'toml',
    'vim',
    'vimdoc',
    'yaml',
  },
  sync_install = true,
  auto_install = true,
  highlight = {
    enable = true,
  },
  incremental_selection = {
    enable = false,
  },
}
